
// Mapeo de roles con tecnologías correspondientes
export const rolesTechsMap: Record<string, string[]> = {
    "Frontend Software Engineer": [
        "HTML5", "CSS3", "JavaScript", "ReactJs", "NextJs", "TypeScript", "VueJs", "NuxtJs", "Angular", "Svelte",
        "Tailwind CSS", "Material UI", "Chakra UI", "Bootstrap", "Ant Design", "Radix UI",
        "Redux", "Recoil", "Zustand", "MobX", "Vuex", "Pinia",
        "Fetch API", "Axios", "GraphQL", "Apollo Client", "Relay", "tRPC",
        "Vite", "Webpack", "Parcel",
        "React Native", "Expo", "Flutter", "Progressive Web Apps (PWA)",
        "Jest", "React Testing Library", "Cypress", "Playwright", "Storybook",
        "GitHub Actions", "Vercel", "Netlify", "Cloudflare Pages"
    ],
    "Backend Software Engineer": [
        "Java", "NodeJs", "Python", "C#", "ASP.NET Core", "Go", "ExpressJs", "NestJs", "Fastify", "Koa",
        "Django", "Flask", "FastAPI", "Spring Boot", "Spring Framework", 
        "Ruby on Rails", "Laravel", "Symfony", "Scala", "ActiveMQ", 
        "GraphQL", "Apollo Server", "tRPC",
        "MongoDB", "PostgreSQL", "MySQL", "SQLite", "Redis", "Cassandra", "DynamoDB",
        "Kafka", "RabbitMQ", "Amazon SQS", "Google Pub/Sub",
        "Docker", "Kubernetes", "Terraform",
        "AWS Lambda", "Google Cloud Functions", "Azure Functions",
        "REST API", "gRPC", "WebSockets",
        "Jest", "Mocha", "Chai", "Supertest",
        "GitHub Actions", "CircleCI", "Jenkins", "ArgoCD"
    ],
    "Full-Stack Software Engineer": [
        "ReactJs", "NextJs", "TypeScript", "VueJs", "NuxtJs", "Angular", "Svelte",
        "Tailwind CSS", "Material UI", "Chakra UI", "Bootstrap", "Ant Design", "Radix UI",
        "Redux", "Recoil", "Zustand", "MobX", "Vuex", "Pinia",
        "Fetch API", "Axios", "GraphQL", "Apollo Client", "Relay", "tRPC",
        "Vite", "Webpack", "Parcel",
        "React Native", "Expo", "Flutter", "Progressive Web Apps (PWA)",
        "Jest", "React Testing Library", "Cypress", "Playwright", "Storybook",
        "GitHub Actions", "Vercel", "Netlify", "Cloudflare Pages",
        "NodeJs", "ExpressJs", "NestJs", "Fastify", "Koa",
        "Python", "Django", "Flask", "FastAPI",
        "Java", "Spring Boot", "Spring Framework", "Micronaut", "Quarkus",
        "C#", "ASP.NET Core", "Blazor",
        "C++", "Poco", "CppRESTSDK",
        "Go", "Gin", "Fiber", "Echo",
        "Ruby", "Ruby on Rails",
        "PHP", "Laravel", "Symfony",
        "Rust", "Actix", "Axum",
        "Scala", "Play Framework", "Akka HTTP",
        "MongoDB", "PostgreSQL", "MySQL", "SQLite", "Redis", "Cassandra", "DynamoDB",
        "Kafka", "RabbitMQ", "Amazon SQS", "Google Pub/Sub",
        "Docker", "Kubernetes", "Terraform",
        "AWS Lambda", "Google Cloud Functions", "Azure Functions",
        "REST API", "gRPC", "WebSockets",
        "Mocha", "Chai", "Supertest",
        "CircleCI", "Jenkins", "ArgoCD"
    ],
    "Mobile Software Engineer": [
        "React Native", "Expo", "Flutter", "Swift", "Kotlin", "Java", "Objective-C",
        "TypeScript", "JavaScript", "Dart",
        "Redux", "MobX", "Vuex",
        "REST API", "GraphQL", "Apollo Client",
        "Firebase", "Google Cloud", "AWS Amplify",
        "SQLite", "Realm", "Core Data",
        "Fastlane", "Bitrise", "GitHub Actions",
        "Jest", "Detox", "Cavy", "Appium",
        "Storybook", "Zeplin", "Figma"
    ],
    "DevOps Engineer": [
        "Docker", "Kubernetes", "Terraform", "Ansible", "Packer",
        "AWS", "Google Cloud", "Azure", "IBM Cloud", "Oracle Cloud",
        "Jenkins", "GitHub Actions", "CircleCI", "GitLab CI",
        "Prometheus", "Grafana", "ELK Stack", "Datadog", "New Relic",
        "Nagios", "Zabbix", "Icinga",
        "Kafka", "RabbitMQ", "Amazon SQS", "Google Pub/Sub",
        "Python", "Bash", "Go", "Ruby", "Perl",
        "Linux", "Unix", "Windows",
        "Nginx", "Apache", "HAProxy",
        "MySQL", "PostgreSQL", "MongoDB", "Redis",
        "Elasticsearch", "Logstash", "Kibana",
        "VPN", "Firewall", "Proxy", "Load Balancer",
        "CI/CD", "IaC", "Monitoring", "Logging",
        "Security", "Networking", "Backup", "Disaster Recovery"
    ],
    "Data Engineer": [
        "Python", "Apache Spark", "Hadoop", "SQL", "Kafka",
        "Java", "Scala", "Go", "Rust",
        "Airflow", "Luigi", "Prefect",
        "Snowflake", "BigQuery", "Redshift", "Azure Synapse",
        "PostgreSQL", "MySQL", "MariaDB", "SQL Server",
        "MongoDB", "Cassandra", "DynamoDB",
        "Elasticsearch", "ClickHouse",
        "Delta Lake", "Iceberg", "Hudi",
        "Apache Flink", "Apache Beam", "Storm",
        "Google Cloud Dataflow", "AWS Glue", "Azure Data Factory",
        "AWS Lambda", "Google Cloud Functions", "Azure Functions",
        "RabbitMQ", "Amazon SQS", "Google Pub/Sub",
        "Terraform", "Docker", "Kubernetes",
        "PySpark", "Dask", "Modin",
        "Jupyter Notebooks", "Pandas", "NumPy",
        "Great Expectations", "dbt",
        "Jenkins", "GitHub Actions", "CircleCI", "ArgoCD"
    ],
    "Machine Learning Engineer": [
        "Python", "TensorFlow", "PyTorch", "scikit-learn", "Kubernetes",
        "JAX", "MXNet", "ONNX", "XGBoost", "LightGBM", "CatBoost",
        "NumPy", "Pandas", "Matplotlib", "Seaborn",
        "OpenCV", "NLTK", "SpaCy", "Transformers (Hugging Face)",
        "Dask", "Modin", "Ray",
        "Apache Spark MLlib", "MLflow", "Kubeflow", "TensorRT",
        "FastAPI", "Flask", "Django REST Framework",
        "PostgreSQL", "MongoDB", "Redis",
        "Apache Kafka", "RabbitMQ", "Amazon SQS", "Google Pub/Sub",
        "AWS SageMaker", "Google Vertex AI", "Azure ML",
        "Docker", "Terraform",
        "REST API", "gRPC", "WebSockets",
        "Jupyter Notebooks", "Streamlit", "Gradio",
        "Great Expectations", "dbt",
        "Jenkins", "GitHub Actions", "CircleCI", "ArgoCD"
    ],
    "Data Scientist": [
        "Python", "R", "Pandas", "NumPy", "Matplotlib",
        "Seaborn", "Plotly", "Bokeh",
        "Jupyter Notebooks", "Google Colab",
        "SQL", "PostgreSQL", "MySQL", "BigQuery", "Snowflake", "Redshift",
        "TensorFlow", "PyTorch", "scikit-learn", "XGBoost", "LightGBM", "CatBoost",
        "Statsmodels", "NLTK", "SpaCy",
        "OpenCV", "Transformers (Hugging Face)",
        "Dask", "Modin", "Ray",
        "Apache Spark MLlib", "MLflow",
        "Excel", "Google Sheets",
        "Dash", "Streamlit", "Gradio",
        "FastAPI", "Flask", "Django REST Framework",
        "Google Vertex AI", "AWS SageMaker", "Azure ML",
        "Docker", "Kubernetes", "Terraform",
        "GitHub Actions", "Jenkins", "CircleCI",
        "Great Expectations", "dbt"
    ],
    "Data Analyst": [
        "SQL", "Tableau", "Excel", "Power BI", "Google Analytics",
        "Python", "R", "Pandas", "NumPy",
        "Matplotlib", "Seaborn", "Plotly", "Bokeh",
        "Google Sheets", "Looker", "Domo",
        "BigQuery", "Snowflake", "Redshift", "PostgreSQL", "MySQL",
        "Apache Superset", "Metabase",
        "Microsoft SQL Server", "Oracle Database",
        "dbt", "Mode Analytics",
        "Jupyter Notebooks", "Google Colab",
        "Google Data Studio", "AWS QuickSight",
        "Alteryx", "KNIME",
        "Google Tag Manager", "Mixpanel", "Adobe Analytics",
        "ETL", "Airflow", "Prefect",
        "GitHub Actions", "Jenkins", "CircleCI"
    ],
  };